### ISSUE TITLE
Support xcworkspace generated by CocoaPods

### ISSUE THREAD

**Issue by xnth97** [Microsoft/WinObjC#14]
While importing my project, which is managed by CocoaPods, the vsimporter failed to find targets in Pods project and some build phases in targets generated by CocoaPods are unsupported and ignored as well. Considering that CocoaPods is quite popular in the community, it would be great if a specific support for CocoaPods is provided in WinObjC.

![](http://ww3.sinaimg.cn/mw1024/a5f335f9gw1eutzh3p2z6j20rb0g3jys.jpg)

**Comment by asimonov-msft** [comment]
What arguments did you pass to vsimporter when you ran it? I tried running the tool on [Wenjin-iOS](https://github.com/xnth97/Wenjin-iOS) but could not reproduce the error.

**Comment by xnth97** [comment]
@asimonov-msft I just followed the wiki since I'm not familiar with the tool but did you run `pod install` before running vsimporter? Otherwise the directory `Pods` won't be created.

**Comment by asimonov-msft** [comment]
@xnth97 I generated the Pods project/workspace under OS X and ran vsimporter under Windows. However I did not get the 'Failed to find target with ... id in "Pods" project.' As far as I could tell, the projects & solution were generated successfully (although they did produce various compilation errors when I tried building them).

**Comment by xnth97** [comment]
@asimonov-msft sorry that I didn't notice the 9-hour-ago commit. The latest vsimporter binary seems to have fixed it and solution generated successfully as you said. AWESOME! But still I got 'Ignoring unsupported PBXHeadersBuildPhase in "..." target'

**Comment by keluo-ms** [comment]
@xnth97 Please let us know if you're still seeing issues.

**Comment by farshid3003** [comment]
I have the same problem by my project

C:\Projects\morhipo-ios>..\winobjc\bin\vsimporter.exe
[W] Failed to find target with 1B5AF4373D1D079F7634CB41 id in "Pods" project.
[W] Failed to find target with 329F61350CF75E41B6B09BDC id in "Pods" project.
[W] Failed to find target with 773023E2800C06B55F98C786 id in "Pods" project.
[W] Failed to find target with D77780FAE95C3D53AFBF5D7A id in "Pods" project.
[W] Failed to find target with F4E035A7DF2ADF477C69E3E4 id in "Pods" project.
[W] Failed to find target with 216E3325FB3D561F1B3CBF8C id in "Pods" project.
[W] Failed to find target with E71D38B5262A56007A9E1479 id in "Pods" project.
[W] Failed to find target with 18CF71E3623CE5240AAF0040 id in "Pods" project.
[W] Failed to find target with 74E37BC6EC18AFF903B1169A id in "Pods" project.
[W] Failed to find target with DFA088E75C8620A8BA39AA5C id in "Pods" project.
[W] Failed to find target with AF55D958E1452E86C35BA404 id in "Pods" project.
[W] Failed to find target with F315E07EB8C882649F38B236 id in "Pods" project.
[W] Failed to find target with 3013F4255B1BB7271BCF2719 id in "Pods" project.
[W] Failed to find target with 58074ECF86CAA40F36463564 id in "Pods" project.
[W] Failed to find target with 2C3986BB65120B2C0822008B id in "Pods" project.
[W] Failed to find target with 8290D3F5D4DDA81CE328D86D id in "Pods" project.
[W] Failed to find target with 137DB292B228CEE443A66859 id in "Pods" project.
[W] Failed to find target with FE0E1E27F920CDCBE9FF6CA0 id in "Pods" project.
[W] Failed to find target with 1585D2BA09EC05C1D38C3AAB id in "Pods" project.
[W] Failed to find target with E0EBD74144E3A7EE37B25863 id in "Pods" project.
[W] Failed to find target with EFAF1C2C433696D6EE6E96B6 id in "Pods" project.
[W] Failed to find target with 4C215B5F94FB6361E524A340 id in "Pods" project.
[W] Failed to find target with 8497F79EA09F527724BEC207 id in "Pods" project.
[W] Failed to find target with E84316D0F50953B1177BCFD2 id in "Pods" project.
[E] No valid targets to import.

C:\Projects\morhipo-ios>
