### ISSUE TITLE
Frameworks compile error: 'Starboard/SmartTypes.h' file not found

### ISSUE THREAD

**Issue by ehren** [Microsoft/WinObjC#2482]
With a clean build of develop using Visual Studio 2017 and the latest available winobjc-tools v0.2.170229-dev-20170404101752, I'm getting:

    ------ Build started: Project: StarboardLib, Configuration: Release Win32 ------
    C:\develop\WinObjC\build\Starboard\lib\..\..\..\Frameworks\Starboard\PlatformSupport.cpp
    C:\develop\WinObjC\Frameworks\include\Starboard.h(208,10): fatal error : 'Starboard/SmartTypes.h' file not found

I'm able to build with 96255883f4dff8c6d16fb49ecd067d56ea2a841d so this looks to be caused by #2419.

**Comment by rajsesh-msft** [comment]
This is dupe of #2444 .

**Comment by DHowett-MSFT** [comment]
This is caused by us not having published an updated WinObjC.Language package. @ehren you may have to build the tools solution before you build WinObjC proper.

**Comment by ehren** [comment]
This isn't a blocker for me in any case (I rebased my functional test pull against the recent 96255883f4dff8c6d16fb49ecd067d56ea2a841d mentioned above - the functional tests also work fine in that commit)

**Comment by rajsesh-msft** [comment]
chocolatey upgrade winobjc-tools --pre --version=0.2.170229-dev-20170404101752 --force should get you to the latest package from develop.  The issue would resolve itself once we have an official version published from master, which would be any day now.

**Comment by rajsesh-msft** [comment]
Scratch that.  As @DHowett-MSFT stated, the header is from WinOBJC.Language package, which is not coming from chocolatey.

**Comment by ehren** [comment]
I was able to complete the build after the successful tools.sln build.

**Comment by DHowett-MSFT** [comment]
Closing as resolved! We'll point future folks here when/if they run into it.
